version: "3.8"

services:
  tf:
    image: tensorflow/tensorflow:2.9.2-gpu-jupyter
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - "./:/tf"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
  serving:
    image: tensorflow/serving:2.8.2
    restart: on-failure
    ports:
      - "8501:8501"
    volumes:
      - "./.data/models:/models"
    environment:
      MODEL_NAME: vk_captcha_net
      TF_CPP_MIN_VLOG_LEVEL: 1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]